title: Sai Kumar
description: Portfolio
baseurl: ""
url: "https://sai-kumar1.github.io"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

collections:
  projects:
    output: true
    permalink: "/project/:name/"
  blogs:
    output: true
    permalink: "/blog/:name/"
